"""add drink sales table

Revision ID: 626c1de963b6
Revises: bebc81cec2fb
Create Date: 2025-12-09 18:23:15.086518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626c1de963b6'
down_revision = 'bebc81cec2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_type', sa.Enum('retail', 'wholesale', name='drink_sale_type'), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'bank payment', 'cash', name='drink_payment_method'), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sold_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], name=op.f('fk_drink_sales_drink_id_drinks')),
    sa.ForeignKeyConstraint(['sold_by'], ['staff.id'], name=op.f('fk_drink_sales_sold_by_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drink_sales')),
    sa.UniqueConstraint('reference_number', name=op.f('uq_drink_sales_reference_number'))
    )
    op.create_table('tot_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_bottle_id', sa.Integer(), nullable=False),
    sa.Column('shot_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'bank payment', 'cash', name='tot_payment_method'), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('sold_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['open_bottle_id'], ['open_bottle.id'], name=op.f('fk_tot_sales_open_bottle_id_open_bottle')),
    sa.ForeignKeyConstraint(['sold_by'], ['staff.id'], name=op.f('fk_tot_sales_sold_by_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tot_sales')),
    sa.UniqueConstraint('reference_number', name=op.f('uq_tot_sales_reference_number'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tot_sales')
    op.drop_table('drink_sales')
    # ### end Alembic commands ###
