"""add carwash income table

Revision ID: 6df19f3a8ec0
Revises: ebc29fb6c269
Create Date: 2025-11-17 15:23:11.470706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df19f3a8ec0'
down_revision = 'ebc29fb6c269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carwash_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('amount_charged', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'cash', 'card payment', name='carwash_payment_method'), nullable=True),
    sa.Column('payment_reference_number', sa.String(), nullable=True),
    sa.Column('service', sa.Enum(name='carwash_service_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_carwash_income_staff_id_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carwash_income')),
    sa.UniqueConstraint('payment_reference_number', name=op.f('uq_carwash_income_payment_reference_number'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carwash_income')
    # ### end Alembic commands ###
