"""add unique constraint to open_bottle.drink_id

Revision ID: 6ed9217cdbb0
Revises: f42872f706ce
Create Date: 2025-11-30 22:18:03.805516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed9217cdbb0'
down_revision = 'f42872f706ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_bottle', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_open_bottle_drink_id'), ['drink_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_bottle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_open_bottle_drink_id'), type_='unique')

    # ### end Alembic commands ###
