"""add drink purchases table

Revision ID: bebc81cec2fb
Revises: 6ed9217cdbb0
Create Date: 2025-12-01 00:34:58.814776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebc81cec2fb'
down_revision = '6ed9217cdbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'bank payment', 'cash', name='drink_purchase_payment_method'), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], name=op.f('fk_drink_purchases_drink_id_drinks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drink_purchases')),
    sa.UniqueConstraint('reference_number', name=op.f('uq_drink_purchases_reference_number'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drink_purchases')
    # ### end Alembic commands ###
