"""add date column to carwash_income table

Revision ID: e31113d31af3
Revises: 6df19f3a8ec0
Create Date: 2025-11-17 15:44:23.023834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31113d31af3'
down_revision = '6df19f3a8ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carwash_income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carwash_income', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
