"""add user, staff and drinks tables

Revision ID: ebc29fb6c269
Revises: 
Create Date: 2025-11-16 22:22:38.643905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc29fb6c269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('drink_type', sa.Enum('Whiskey', 'Beer', 'Vodka', 'Gin', 'Liquer', 'Wine', 'Spirit', 'Rum', 'Brandy', 'Cognac', 'Cider', 'Tequila', name='drinks_type'), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Enum('250 ml', '350 ml', '500 ml', '750 ml', '1L', name='drink_volume'), nullable=False),
    sa.Column('markup', sa.Float(), nullable=False),
    sa.Column('shot_price', sa.Float(), nullable=False),
    sa.Column('shot_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drinks'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('bar', 'restaurant', 'carwash', 'manager', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_number', sa.String(length=8), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('department', sa.Enum('bar', 'restaurant', 'carwash', 'manager', name='staff_department'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff')),
    sa.UniqueConstraint('id_number', name=op.f('uq_staff_id_number')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_staff_phone_number'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('users')
    op.drop_table('drinks')
    # ### end Alembic commands ###
