"""add open bottle table and set shot quantity default to 25

Revision ID: f42872f706ce
Revises: e31113d31af3
Create Date: 2025-11-30 21:57:41.849884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42872f706ce'
down_revision = 'e31113d31af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_bottle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('shots_remaining', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], name=op.f('fk_open_bottle_drink_id_drinks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_bottle'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_bottle')
    # ### end Alembic commands ###
